pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION   = 'us-east-1'
  }

  stages {

    stage('Checkout Code') {
      steps {
        git url: 'https://github.com/your-org/infra-repo.git', branch: 'main'
      }
    }

    stage('Terraform Init') {
      steps {
        sh 'terraform init'
      }
    }

    stage('Terraform Plan') {
      steps {
        sh 'terraform plan'
      }
    }

    stage('Terraform Apply') {
      steps {
        input message: "Approve Terraform Apply?"
        sh 'terraform apply -auto-approve'
      }
    }
  }
}
